"""Second curated expansion: five classic roots, shared canonical packages.
Executed by curate.py; source audit and deliberate boundaries are in
research/dallas-wave2-notes.md. No network work takes place here.
"""

source('w2-suns13','Phoenix 2013 media guide: Barkley, Kidd and Marbury transactions','https://library.sfo2.cdn.digitaloceanspaces.com/publications/basketball/yearbooks/KPHXSMG-2013.pdf','Phoenix Suns media guide')
source('w2-kidd08','Completed Kidd trade: eight players, two firsts and cash','https://www.dallasobserver.com/news/done-deal-kidds-a-mav-again-7137854','Dallas Observer','reporting')
source('w2-nets-picks','Contemporaneous Nets pick ledger: Carter and Kidd protections','https://www.netsdaily.com/2008/2/24/1346557/post-kmart-vs-post-jkidd','NetsDaily','reporting')
source('w2-draft08','2008 draft selections, including Dallas-origin No. 21','https://www.deseret.com/2008/6/27/20260779/2008-nba-draft-selections/','Deseret News','reporting')
source('w2-carter04','Nets announce the completed Vince Carter trade','https://www.nba.com/nets/news/carter121704.html')
source('w2-carter04-report','Carter completed trade: Philadelphia 2005 and Denver 2006 picks','https://www.netsdaily.com/2004/12/17/1347749/nets-acquire-vince-carter-from','NetsDaily','reporting')
source('w2-draft05','2005 draft: Joey Graham and the Philadelphia-origin selection','https://score-origin.espn.com/nba/draft/rounds/_/season/2005','ESPN','reporting')
source('w2-carter09','Nets trade Carter and Anderson to Orlando','https://www.upi.com/Sports_News/2009/06/25/Nets-trade-Vince-Carter-to-Orlando/69081245979758/','United Press International','reporting')
source('w2-carter10','Phoenix explains the December 18 Orlando exchange','https://www.nba.com/suns/news/feature_improve_trade_101218.html')
source('w2-barkley92','Contemporaneous report: Barkley traded to Phoenix','https://www.upi.com/Archives/1992/06/17/Barkley-traded-to-Suns/3478708753600/','United Press International','reporting')
source('w2-barkley96','Houston retrospective includes the 1999 second-round pick','https://www.houstonpress.com/news/westbrook-latest-former-franchise-icon-to-become-a-rocket-11323229/','Houston Press','reporting')
source('w2-barkley96-pick','Contemporary Horry profile confirms Barkley trade second-round pick','https://www.latimes.com/archives/la-xpm-1997-01-11-sp-17533-story.html','Los Angeles Times','reporting')
source('w2-phx99-origin','1999 draft order confirms Houston’s Phoenix-origin second','https://www.cbsnews.com/news/1999-nba-draft-order/','CBS News','reporting')
source('w2-warriors17','Warriors 2016–17 media guide: Chamberlain transaction ledger','https://ak-static-int.nba.com/wp-content/uploads/sites/3/2016/10/2016-17-Media-Guide-Warriors.pdf','Golden State Warriors media guide')
source('w2-sixers20','Philadelphia 2020 media guide: Chamberlain transactions','https://library.sfo2.cdn.digitaloceanspaces.com/publications/basketball/yearbooks/KPHI7MG-2020.pdf','Philadelphia 76ers media guide')
source('w2-wilt68','NBA historical calendar: July 9, 1968 Chamberlain package','https://www.nba.com/news/history-this-date-in-nba-july')
source('w2-shaffer-rights','NBA account clarifies Shaffer’s player rights in the 1965 trade','https://www.nba.com/news/kia-rookie-ladder-november-20-2024-edition')
source('w2-melo11','Denver announces the completed three-team Anthony exchange','https://www.nba.com/nuggets/news/nuggets_trade_02_22_2011.html')
source('w2-denver24','Denver 2023–24 media guide: 2011 transactions and draft history','https://cdn.nba.com/teams/uploads/sites/1610612743/2024/01/DN_2324_MediaGuide.pdf','Denver Nuggets media guide')
source('w2-melo-min','Minnesota reports final Koufos addition and cash','https://www.startribune.com/deal-s-done-koufos-added-to-trade-that-sends-brewer-to-nyc/116703294','Star Tribune','reporting')
source('w2-melo-min-pick','Koufos addition includes Denver 2015 unprotected second','https://www.nbcsports.com/nba/news/minor-addition-to-e2-80-98melo-trade-wolves-send-kosta-koufos-to-denver','NBC Sports','reporting')
source('w2-melo-cash','Denver recap confirms Golden State seconds and cash','https://www.nba.com/nuggets/news/carmelo_adventure_02_23_2011.html')
source('w2-murray-chain','Denver traces the Murray pick to its Anthony swap right','https://www.nba.com/nuggets/news/tracing-roots-behind-the-2018-19-nuggets-roster-032019')
source('w2-quincy12','Denver draft-night press conference: Quincy Miller at No. 38','https://www.nba.com/nuggets/news/denver-nuggets-draft-night-transcript')
source('w2-bargnani13','Completed Bargnani exchange and Richardson sign-and-trade','https://www.hoopsrumors.com/2013/07/knicks-acquire-andrea-bargnani-1.html','Hoops Rumors','reporting')
source('w2-bargnani-ledger','Bargnani package and actual pick outcomes','https://www.shamsports.com/players/steve-novak','ShamSports','reporting')
source('w2-bargnani-origins','Contemporaneous Bargnani reporting identifies Oklahoma City and New York seconds','https://sports.yahoo.com/blogs/nba-ball-dont-lie/york-knicks-trading-andrea-bargnani-because-course-155517381.html','Yahoo Sports','reporting')
source('w2-bargnani-terms','Pick ledger: Toronto receives less favorable Knicks/Nuggets first','https://www.basketballinsiders.com/nba-draft-picks-owed/','Basketball Insiders','reporting')
source('w2-draft14-order','NBA Communications: Oklahoma City second belongs to Toronto via New York','https://pr.nba.com/nba-draft-2014-order-of-selection/','NBA Communications')
source('w2-lottery16','2016 lottery: New York No. 7 to Denver, Denver No. 9 to Toronto','https://www.espn.com/nba/draft2016/story/_/id/15581021/philadelphia-76ers-win-lottery-pick-first-2016-nba-draft','ESPN','reporting')
source('w2-lottery16-date','May 17 lottery fixes the 2016 selection order','https://www.si.com/nba/2016/05/17/nba-draft-lottery-order-picks-results','Sports Illustrated','reporting')
source('w2-draft16','NBA team draft-night account: Murray No. 7, Poeltl No. 9','https://www.nba.com/bulls/news/pick-pick-nba-draft-analysis')
source('w2-melo17','Oklahoma City announces Carmelo Anthony acquisition','https://www.nba.com/thunder/news/carmelo-anthony-170925')
source('w2-knicks18','Knicks 2017–18 media guide: September 25 Anthony exchange','https://ak-static-int.nba.com/wp-content/uploads/sites/3/2017/10/2017-18-Media-Guide-Knicks.pdf','New York Knicks media guide')
source('w2-robinson18','NBA identifies Robinson as the second-round return from Anthony trade','https://www.nba.com/news/2018-summer-standouts-day-10-july-12')
source('w2-robinson-draft','2018 draft-night selections: Mitchell Robinson at No. 36','https://www.nbcsports.com/nba/news/2018-nba-draft-pick-by-pick-tracker-with-analysis-of-selections-trades','NBC Sports','reporting')
source('w2-melo18','NBA announces completed Anthony–Schröder three-team trade','https://www.nba.com/news/carmelo-anthony-trade-hawks-dennis-schroeder-trade-thunder-official')
source('w2-sixers-muscala','Philadelphia announces its full leg of the Muscala trade','https://www.nba.com/sixers/team-acquires-mike-muscala-three-team-deal')
source('w2-hawks19','Atlanta 2019 media guide: July 25, 2018 completed exchange','https://library.sfo2.cdn.digitaloceanspaces.com/publications/basketball/yearbooks/KATLHMG-2019.pdf','Atlanta Hawks media guide')
source('w2-melo22-protection','Oklahoma City 2022 first: protection and second-round fallback','https://thunderousintentions.com/2021/06/19/okc-thunder-draft-picks-celtics-trade/','Thunderous Intentions','reporting')

for _id,_name in [
 ('kidd','Jason Kidd'),('dumas','Tony Dumas'),('meyer','Loren Meyer'),('finley','Michael Finley'),('green-ac','A.C. Green'),('cassell','Sam Cassell'),('jackson-jim','Jim Jackson'),('gatling','Chris Gatling'),('mccloud','George McCloud'),('montross','Eric Montross'),('bradley-shawn','Shawn Bradley'),('obannon','Ed O’Bannon'),('pack','Robert Pack'),('reeves','Khalid Reeves'),('dudley-chris','Chris Dudley'),('marbury','Stephon Marbury'),('newman','Johnny Newman'),('samake','Soumaila Samake'),('allen-malik','Malik Allen'),('harris-devin','Devin Harris'),('diop','DeSagana Diop'),('ager','Maurice Ager'),('van-horn','Keith Van Horn'),('hassell','Trenton Hassell'),('anderson-ryan','Ryan Anderson'),
 ('carter-vince','Vince Carter'),('mourning','Alonzo Mourning'),('williams-aaron','Aaron Williams'),('williams-eric','Eric Williams'),('graham-joey','Joey Graham'),('lee-courtney','Courtney Lee'),('alston','Rafer Alston'),('battie','Tony Battie'),('gortat','Marcin Gortat'),('pietrus','Mickaël Piétrus'),('richardson-jason','Jason Richardson'),('clark-earl','Earl Clark'),
 ('barkley','Charles Barkley'),('hornacek','Jeff Hornacek'),('perry-tim','Tim Perry'),('lang-andrew','Andrew Lang'),('horry','Robert Horry'),('bryant-mark','Mark Bryant'),('brown-chucky','Chucky Brown'),
 ('wilt','Wilt Chamberlain'),('dierking','Connie Dierking'),('neumann','Paul Neumann'),('shaffer','Lee Shaffer'),('imhoff','Darrall Imhoff'),('clark-archie','Archie Clark'),('chambers-jerry','Jerry Chambers'),
 ('melo','Carmelo Anthony'),('billups','Chauncey Billups'),('carter-anthony','Anthony Carter'),('balkman','Renaldo Balkman'),('williams-shelden','Shelden Williams'),('chandler-wilson','Wilson Chandler'),('felton','Raymond Felton'),('mozgov','Timofey Mozgov'),('koufos','Kosta Koufos'),('brewer-corey','Corey Brewer'),('curry-eddy','Eddy Curry'),('randolph-anthony','Anthony Randolph'),('miller-quincy','Quincy Miller'),('bargnani','Andrea Bargnani'),('novak','Steve Novak'),('camby','Marcus Camby'),('richardson-quentin','Quentin Richardson'),('murray-jamal','Jamal Murray'),('kanter','Enes Kanter'),('mcdermott','Doug McDermott'),('robinson-mitchell','Mitchell Robinson'),('muscala','Mike Muscala'),('luwawu-cabarrot','Timothé Luwawu-Cabarrot'),('anderson-justin','Justin Anderson')
]:
 if _id not in assets:player(_id,_name)

if 'DEN' not in teams:teams['DEN']=dict(id='DEN',city='Denver',name='Denver Nuggets',short='Nuggets',color='#f0ca72')
# Historical labels are valid season windows, not assertions of legal rename dates.
teams['BKN']['aliases']=teams['BKN'].get('aliases',[])+[dict(from_='1977-07-01',to='2012-06-30',name='New Jersey Nets')]
teams['GSW']['aliases']=teams['GSW'].get('aliases',[])+[dict(from_='1962-07-01',to='1971-06-30',name='San Francisco Warriors')]

# Kidd's two Dallas trades are different packages, separated by twelve seasons.
obligation('w2-phx98-second','Phoenix conditional 1997/98 second','PHX',1997,2,conditions='Dallas’s media guide describes a 1997 or 1998 second. It conveyed as Phoenix’s 1998 No. 53. The original timing trigger is not enumerated; no extra 1997 pick is implied.')
tx('kidd-phoenix','1996-12-26','Dallas breaks up the backcourt.','Kidd heads to Phoenix in a six-player exchange. Dallas receives Finley, Green, Cassell and a conditional second. Cassell’s stay will be brief.','DAL PHX',ms('kidd dumas meyer','DAL','PHX')+ms('finley green-ac cassell w2-phx98-second','PHX','DAL'),'dx-dallas25 w2-suns13 draft98',short='Kidd goes to Phoenix')
tx('cassell-new-jersey','1997-02-17','Nine players change addresses.','Less than two months later, Cassell joins four other Mavericks on the way to New Jersey. Bradley, Pack, Reeves and O’Bannon come to Dallas.','DAL BKN',ms('cassell jackson-jim gatling mccloud montross','DAL','BKN')+ms('bradley-shawn pack reeves obannon','BKN','DAL'),'dx-dallas25',short='Cassell joins the nine-player deal')
selection('buckner-draft','1998-06-24','DAL','w2-phx98-second','buckner','Greg Buckner',53,1998,'PHX',2,'draft98 dx-dallas25','The Phoenix-origin second settles at No. 53. Dallas selects Greg Buckner.')
tx('kidd-new-jersey','2001-07-18','Two point guards, five players.','Phoenix sends Kidd and Dudley to New Jersey. Marbury, Newman and Samake go the other way.','PHX BKN',ms('kidd dudley-chris','PHX','BKN')+ms('marbury newman samake','BKN','PHX'),'w2-suns13',short='Kidd and Marbury change teams')
obligation('w2-dal08-kidd','Dallas 2008 protected first','DAL',2008,conditions='Lottery protected in 2008. Conveyed at No. 21 that June. Unused rollover language is not asserted.',protection=[dict(year=2008,protectedRanges=[[1,14]])])
obligation('w2-dal10-kidd','Dallas 2010 first','DAL',2010)
cash('w2-kidd08-cash','$3 million from Dallas to New Jersey.')
tx('kidd-dallas','2008-02-19','The long way back to Dallas.','Kidd returns with Allen and Wright. Five Dallas players, two first-round obligations and cash form the return package.','DAL BKN',ms('kidd allen-malik wright-antoine','BKN','DAL')+ms('harris-devin diop ager van-horn hassell w2-dal08-kidd w2-dal10-kidd w2-kidd08-cash','DAL','BKN'),'w2-kidd08 dx-dallas25 w2-nets-picks',notes=['Keith Van Horn was signed and traded. This is the completed February 19 package, after the earlier proposal involving Devean George was abandoned.'],short='Jason Kidd returns to Dallas')
selection('anderson-ryan-draft','2008-06-26','BKN','w2-dal08-kidd','anderson-ryan','Ryan Anderson',21,2008,'DAL',1,'w2-draft08 w2-nets-picks','Dallas’s first conveys at No. 21. New Jersey selects Ryan Anderson, who will join a much larger headline a year later.')

# The 2004 completed release corrects early reporting that reversed the pick years.
obligation('w2-phi05-carter','Philadelphia protected 2005 first','PHI',2005,conditions='Top 8 protected in 2005, top 5 in 2006, unprotected in 2007. Conveyed at No. 16 in 2005.',protection=[dict(year=2005,protectedRanges=[[1,8]]),dict(year=2006,protectedRanges=[[1,5]]),dict(year=2007,protectedRanges=[])])
obligation('w2-den06-carter','Denver protected 2006 first','DEN',2006,conditions='Top 5 protected in 2006, top 2 in 2007, unprotected in 2008. Its subsequent Toronto transfers are outside this branch.',protection=[dict(year=2006,protectedRanges=[[1,5]]),dict(year=2007,protectedRanges=[[1,2]]),dict(year=2008,protectedRanges=[])])
tx('carter-new-jersey','2004-12-17','Vince leaves Toronto.','New Jersey adds Carter. Toronto receives Mourning, two Williamses and protected firsts originating with Philadelphia and Denver.','TOR BKN',ms('carter-vince','TOR','BKN')+ms('mourning williams-aaron williams-eric w2-phi05-carter w2-den06-carter','BKN','TOR'),'w2-carter04 w2-carter04-report w2-nets-picks',short='Vince Carter goes to New Jersey')
selection('graham-joey-draft','2005-06-28','TOR','w2-phi05-carter','graham-joey','Joey Graham',16,2005,'PHI',1,'w2-draft05 w2-nets-picks','The Philadelphia-origin first conveys at No. 16. Toronto selects Joey Graham.')
tx('carter-orlando','2009-06-25','A Dallas pick travels with Vince.','Carter and Ryan Anderson go to Orlando together. Lee, Alston and Battie move to New Jersey. Anderson entered this route through Dallas’s Kidd trade.','BKN ORL',ms('carter-vince anderson-ryan','BKN','ORL')+ms('lee-courtney alston battie','ORL','BKN'),'w2-carter09 dx-orlando13',short='Carter and Anderson go to Orlando')
obligation('w2-orl11-carter','Orlando 2011 first','ORL',2011,conditions='Orlando’s 2011 first-round obligation. The cited completed trade summaries do not enumerate protection or rollover terms; this branch stops at its transfer.')
cash('w2-carter10-cash')
tx('carter-phoenix','2010-12-18','Six players. Another new jersey.','Carter, Gortat and Piétrus go to Phoenix with a first and cash. Richardson, Türkoğlu and Clark head to Orlando.','ORL PHX',ms('carter-vince gortat pietrus w2-orl11-carter w2-carter10-cash','ORL','PHX')+ms('richardson-jason turkoglu clark-earl','PHX','ORL'),'w2-carter10 dx-orlando13',notes=['Orlando’s separate Rashard Lewis–Gilbert Arenas trade on the same day is not merged into this package. Carter’s later Dallas arrival was free agency, not a return from this exchange.'],short='Vince goes to Phoenix')

# Barkley's return package intersects Kidd's first Dallas departure through Cassell.
tx('barkley-phoenix','1992-06-17','Barkley heads west.','Philadelphia sends Barkley to Phoenix for Hornacek, Perry and Lang. Four years later, another package will take him to Houston.','PHI PHX',ms('barkley','PHI','PHX')+ms('hornacek perry-tim lang-andrew','PHX','PHI'),'w2-barkley92 w2-suns13',short='Barkley goes to Phoenix')
obligation('w2-phx99-barkley','Phoenix 1999 second','PHX',1999,2,conditions='The 1999 second-round choice included with Barkley. The cited historical package does not enumerate protection language; its later use is outside this story.')
tx('barkley-houston','1996-08-19','Houston sends a whole rotation.','Barkley and a second-round obligation go to Houston. Cassell, Horry, Bryant and Brown move to Phoenix; Cassell soon enters the Kidd exchange.','PHX HOU',ms('barkley w2-phx99-barkley','PHX','HOU')+ms('cassell horry bryant-mark brown-chucky','HOU','PHX'),'w2-suns13 w2-barkley96 w2-barkley96-pick w2-phx99-origin',short='Barkley for the Cassell–Horry package')

# The San Francisco Warriors and Philadelphia 76ers are distinct franchises.
cash('w2-wilt65-cash','Cash was included; no amount is asserted from the cited team ledger.')
cash('w2-wilt68-cash','Cash was included; the NBA historical calendar does not disclose an amount.')
assets['shaffer']['detail']='His player rights were included in the Chamberlain trade after he had left the NBA. These were not draft rights.'
tx('wilt-philadelphia','1965-01-15','A different Philadelphia franchise.','The San Francisco Warriors send Chamberlain to the 76ers for Dierking, Neumann, Shaffer’s player rights and cash. Philadelphia here is a different franchise from the Warriors.','GSW PHI',ms('wilt','GSW','PHI')+ms('dierking neumann w2-wilt65-cash','PHI','GSW')+[m('shaffer','PHI','GSW',form='player-rights',note='Player rights after his NBA departure; not draft rights.')],'w2-warriors17 w2-sixers20 w2-shaffer-rights',notes=['The effective date follows Golden State’s historical transaction ledger. Philadelphia here means the 76ers; the Warriors had previously played in Philadelphia.'],short='Wilt goes to the 76ers')
tx('wilt-lakers','1968-07-09','The biggest name moves again.','Philadelphia sends Chamberlain to Los Angeles. Imhoff, Clark, Chambers and cash make up the Lakers’ return package.','PHI LAL',ms('wilt','PHI','LAL')+ms('imhoff clark-archie chambers-jerry w2-wilt68-cash','LAL','PHI'),'w2-sixers20 w2-wilt68',short='Wilt goes to Los Angeles')

# Melo: a three-team package, an independent Bargnani trade, then a two-pick swap.
obligation('w2-nyk14-melo','New York 2014 first','NYK',2014,conditions='New York’s 2014 first-round obligation in the Anthony trade. Subsequent transfers and the eventual selection are outside this branch.')
obligation('w2-gsw12-melo','Golden State 2012 second','GSW',2012,2,conditions='Golden State-origin second held by New York; conveyed at No. 38 in 2012. Original protection language is not asserted.')
obligation('w2-gsw13-melo','Golden State 2013 second','GSW',2013,2,conditions='Golden State-origin 2013 second held by New York. Its later transfers are outside this branch.')
obligation('w2-den15-melo','Denver 2015 second','DEN',2015,2)
swap('w2-nyk16-melo-swap','NYK',2016,'Denver can exchange its own 2016 first for New York’s, taking the more favorable pick. New York retains the other pick, later promised to Toronto in the Bargnani trade.')
cash('w2-melo11-den-cash','$3 million from New York to Denver.')
cash('w2-melo11-min-cash','$3 million from New York to Minnesota.')
tx('carmelo-new-york','2011-02-22','Thirteen players. One headline.','New York gets Anthony and five other players. Denver receives five players, three pick obligations and a swap right; Minnesota completes the final structure.','DEN NYK MIN',ms('melo billups carter-anthony balkman williams-shelden','DEN','NYK')+ms('chandler-wilson felton gallinari mozgov w2-nyk14-melo w2-gsw12-melo w2-gsw13-melo w2-nyk16-melo-swap w2-melo11-den-cash','NYK','DEN')+ms('koufos','MIN','DEN')+ms('brewer-corey','MIN','NYK')+ms('curry-eddy randolph-anthony w2-melo11-min-cash','NYK','MIN')+ms('w2-den15-melo','DEN','MIN'),'w2-melo11 w2-denver24 w2-melo-min w2-melo-min-pick w2-melo-cash w2-murray-chain',notes=['This is the completed February 22 three-team exchange. The 2016 swap is a right to exchange two firsts, not an additional outright first for Denver.'],short='Carmelo Anthony goes to New York')
selection('miller-quincy-draft','2012-06-28','DEN','w2-gsw12-melo','miller-quincy','Quincy Miller',38,2012,'GSW',2,'w2-quincy12 w2-denver24','Denver uses the Golden State-origin second from the Anthony package on Quincy Miller at No. 38.')
obligation('w2-nyk-den16-bargnani','Less favorable NYK / DEN 2016 first',None,2016,conditions='The less favorable of New York’s and Denver’s 2016 firsts, after Denver’s existing swap right. Exactly one first is owed to Toronto.',candidates=['NYK','DEN'])
obligation('w2-okc14-bargnani','Oklahoma City 2014 second','OKC',2014,2,conditions='Oklahoma City-origin 2014 second held by New York. The NBA’s 2014 order confirms its route to Toronto via New York. Later draft-night transfers are outside this branch.')
obligation('w2-nyk17-bargnani','New York 2017 second','NYK',2017,2,conditions='New York’s 2017 second in the Bargnani package. Later transfers are outside this branch.')
tx('bargnani-new-york','2013-07-10','The other half of the swap finds a home.','Toronto sends Bargnani to New York for three players and three pick obligations. Its 2016 first will be whichever pick Denver leaves behind.','TOR NYK',ms('bargnani','TOR','NYK')+ms('novak camby richardson-quentin w2-nyk-den16-bargnani w2-okc14-bargnani w2-nyk17-bargnani','NYK','TOR'),'w2-bargnani13 w2-bargnani-ledger w2-bargnani-origins w2-bargnani-terms w2-draft14-order',notes=['Quentin Richardson was signed and traded. Toronto receives one composite 2016 entitlement, not both New York’s and Denver’s picks.'],short='Bargnani goes to New York')
for _id,_origin,_number in [('w2-nyk16-7','NYK',7),('w2-den16-9','DEN',9)]:
 assets[_id]=dict(id=_id,name=f'2016 No. {_number}',kind='pick',origin=_origin,year=2016,round=1,number=_number)
tx('denver-new-york-swap','2016-05-17','Two tickets, two destinations.','The lottery fixes New York’s pick at No. 7 and Denver’s at No. 9. Denver takes No. 7; Toronto’s separate entitlement receives No. 9.','DEN NYK TOR',[],'w2-lottery16 w2-lottery16-date w2-bargnani-terms w2-murray-chain',kind='resolution',conversions=[dict(**{'from':'w2-nyk16-melo-swap'},to='w2-nyk16-7',team='DEN',kind='conveyance'),dict(**{'from':'w2-nyk-den16-bargnani'},to='w2-den16-9',team='TOR',kind='conveyance')],resolutions=[dict(asset='w2-nyk16-melo-swap',status='exercised',detail='Denver takes New York’s No. 7 instead of its own No. 9. The No. 9 goes to Toronto under the subsequent Bargnani agreement.')],notes=['May 17 records the now-known lottery allocation. It is not presented as a separately verified administrative exercise date. Both sides of the exchange are shown; no third first-round pick is created.'],short='Denver gets No. 7; Toronto gets No. 9')
tx('murray-jamal-draft','2016-06-23','New York’s pick becomes Murray.','Denver selects Jamal Murray at No. 7. The route begins with a swap clause in the Anthony trade five years earlier.','DEN',[],'w2-murray-chain w2-draft16 w2-denver24',kind='draft',conversions=[dict(**{'from':'w2-nyk16-7'},to='murray-jamal',team='DEN',kind='selection')],short='Jamal Murray selected')
tx('poeltl-draft','2016-06-23','Denver’s pick becomes Poeltl.','Toronto selects Jakob Poeltl at No. 9. Two years later, he joins DeRozan and a first in the Leonard package.','TOR',[],'w2-draft16 w2-bargnani-ledger',kind='draft',conversions=[dict(**{'from':'w2-den16-9'},to='poeltl',team='TOR',kind='selection')],order=1,short='Jakob Poeltl selected')
obligation('w2-chi18-melo','Chicago 2018 second','CHI',2018,2,conditions='Chicago-origin second held by Oklahoma City. Conveyed to New York at No. 36 in 2018.')
tx('carmelo-oklahoma-city','2017-09-25','Melo moves. Another pick stays behind.','New York sends Anthony to Oklahoma City for Kanter, McDermott and Chicago’s 2018 second.','NYK OKC',ms('melo','NYK','OKC')+ms('kanter mcdermott w2-chi18-melo','OKC','NYK'),'w2-melo17 w2-knicks18',short='Carmelo goes to Oklahoma City')
selection('robinson-mitchell-draft','2018-06-21','NYK','w2-chi18-melo','robinson-mitchell','Mitchell Robinson',36,2018,'CHI',2,'w2-robinson18 w2-robinson-draft w2-knicks18','The Chicago-origin second becomes No. 36. New York selects Mitchell Robinson.')
obligation('w2-okc22-melo','Oklahoma City protected 2022 first','OKC',2022,conditions='Top 14 protected in 2022. If it does not convey, becomes Oklahoma City’s 2024 and 2025 seconds. This route stops at the 2018 transfer; later resolution and transfers are untraced.',protection=[dict(year=2022,protectedRanges=[[1,14]],fallback='2024 and 2025 OKC seconds')])
tx('carmelo-atlanta','2018-07-25','One more three-team package.','Anthony and a protected first go to Atlanta. Schröder and Luwawu-Cabarrot reach Oklahoma City; Muscala goes to Philadelphia, with Anderson going to Atlanta.','OKC ATL PHI',ms('melo w2-okc22-melo','OKC','ATL')+ms('schroder','ATL','OKC')+ms('muscala','ATL','PHI')+ms('luwawu-cabarrot','PHI','OKC')+ms('anderson-justin','PHI','ATL'),'w2-melo18 w2-sixers-muscala w2-hawks19 w2-melo22-protection',notes=['Anthony was subsequently waived by Atlanta. His later Houston signing is not drawn as a trade return.'],short='Carmelo joins the Schröder exchange')

story('kidd','The Kidd round trip','A long way home.','Dallas to Phoenix. New Jersey to Dallas. Follow the packages, then watch one Dallas pick travel with Vince Carter.','Dallas',1996,2010,'DAL','#6eb9fa','kidd-phoenix cassell-new-jersey buckner-draft kidd-new-jersey kidd-dallas anderson-ryan-draft carter-orlando carter-phoenix','kidd-phoenix','Kidd’s three trades, the Cassell branch, two verified Dallas/Phoenix pick conveyances and Ryan Anderson’s Orlando exchange. Stops with Carter’s 2010 Phoenix package; later free agency and other pick branches are untraced.','The Dallas first in Kidd’s return package became Ryan Anderson, who later traveled to Orlando with Vince Carter.')
story('carter','Vince changes the picture','The next flight.','Toronto, New Jersey, Orlando, Phoenix. Follow Vince—and the first-round pick whose route begins in Dallas.','Classic',2004,2010,'TOR','#f07c91','carter-new-jersey graham-joey-draft kidd-dallas anderson-ryan-draft carter-orlando carter-phoenix','carter-new-jersey','Three Carter trades, Joey Graham’s Philadelphia-origin pick and the Dallas origin of Ryan Anderson’s selection. Stops in December 2010; remaining picks and subsequent free-agent signings are untraced.','Carter and Anderson were a two-player package. Anderson’s draft pick had come from Dallas in a different star’s trade.')
story('carmelo','The clause that kept going','Five years in the fine print.','A star to New York. A swap that becomes Jamal Murray. And the other pick’s route into Toronto’s Kawhi package.','Classic',2011,2024,'DEN','#f0ca72','carmelo-new-york miller-quincy-draft bargnani-new-york denver-new-york-swap murray-jamal-draft poeltl-draft carmelo-oklahoma-city robinson-mitchell-draft kawhi-toronto carmelo-atlanta keldon-draft poeltl-toronto dillingham-draft dillingham-minnesota','carmelo-new-york','The final 2011 package, selected 2012/2016/2018 pick outcomes, Anthony’s 2017/2018 trades, and Poeltl’s existing route through the 2024 draft. Other players, seconds, the 2014 first and the protected OKC 2022 obligation are not followed after their displayed transfers.','Denver’s swap and Toronto’s separate Bargnani trade divided two firsts. Murray and Poeltl are documented outcomes of different entitlements.')
story('barkley','Barkley’s Dallas connection','Follow Sam Cassell.','Barkley goes to Houston. One player in Phoenix’s return soon becomes part of Dallas’s Jason Kidd exchange.','Classic',1992,2001,'PHX','#ef9a64','barkley-phoenix barkley-houston kidd-phoenix cassell-new-jersey buckner-draft kidd-new-jersey','barkley-phoenix','Both Barkley trades, Cassell’s Phoenix–Dallas–New Jersey route, the Kidd exchange and the Phoenix second’s 1998 conveyance. Stops at Kidd’s 2001 New Jersey arrival; Horry and other received assets remain bounded branches.','Cassell connects the Barkley and Kidd packages. That does not mean Barkley alone was exchanged for everything that followed.')
story('wilt','The original giant moves','Even Wilt was traded.','Two blockbuster exchanges, three franchises. Follow Chamberlain from San Francisco to Philadelphia to Los Angeles.','Classic',1965,1968,'PHI','#78aaff','wilt-philadelphia wilt-lakers','wilt-philadelphia','Only the complete 1965 and 1968 Chamberlain packages. Cash is included without invented amounts. Earlier franchise relocation and subsequent player transactions are outside the selected route.','The San Francisco Warriors and Philadelphia 76ers were separate franchises. These were two trades, not a franchise returning home.')
