"""Wave 3: five modern routes; curated facts, no network access or output writes.

Execute after the earlier research/expansions files and before normalization.
Every multi-asset exchange remains a transaction node. Boundary notes deliberately
stop unresolved pick fulfillment and untraced intervening player moves.
"""

for aid, name in [
 ('lavine', 'Zach LaVine'), ('dunn', 'Kris Dunn'), ('patton', 'Justin Patton'),
 ('covington', 'Robert Covington'), ('saric', 'Dario Šarić'), ('bayless', 'Jerryd Bayless'),
 ('leonard-meyers', 'Meyers Leonard'), ('whiteside', 'Hassan Whiteside'),
 ('harkless', 'Moe Harkless'), ('lessort', 'Mathias Lessort'),
 ('jones-derrick', 'Derrick Jones Jr.'), ('lyles', 'Trey Lyles'), ('lydon', 'Tyler Lydon'),
 ('siakam', 'Pascal Siakam'), ('brown-bruce', 'Bruce Brown'), ('lewis-kira', 'Kira Lewis Jr.'),
 ('porter-otto', 'Otto Porter Jr.'), ('walter', 'Ja’Kobe Walter'), ('collier', 'Isaiah Collier'),
 ('morris-marcus', 'Marcus Morris Sr.'), ('batum', 'Nicolas Batum'), ('petrusev', 'Filip Petrušev'),
 ('jackson-reggie', 'Reggie Jackson'), ('butler-jared', 'Jared Butler'), ('garland', 'Darius Garland'),
 ('fox', 'De’Aaron Fox'), ('mclaughlin-jordan', 'Jordan McLaughlin'), ('huerter', 'Kevin Huerter'),
 ('collins-zach', 'Zach Collins'), ('jones-tre', 'Tre Jones'), ('cissoko', 'Sidy Cissoko'),
 ('murray-dejounte', 'Dejounte Murray'), ('landale', 'Jock Landale'), ('raynaud', 'Maxime Raynaud'),
]:
 if aid not in assets: player(aid, name)

source('w3-butler17', 'Chicago announces LaVine, Dunn and Markkanen rights acquisition', 'https://www.nba.com/news/chicago-bulls-acquire-kris-dunn-zach-lavine-lauri-markkanen-minnesota')
source('w3-butler17-min', 'Minnesota announces Butler and Patton draft-rights exchange', 'https://api-hub-uat.nba.com/news/timbewolves-acquire-three-time-nba-all-star-jimmy-butler')
source('w3-butler18', 'Philadelphia confirms the complete Butler exchange', 'https://api-hub.nba.com/news/philadelphia-76ers-jimmy-butler-trade-official-release')
source('w3-butler18-second', 'Butler exchange: 2022 Philadelphia / Denver second-round condition', 'https://www.phillyvoice.com/sixers-trade-dario-saric-robert-covington-minnesota-all-star-jimmy-butler/', 'PhillyVoice', 'reporting')
source('w3-butler19', 'The completed four-team Butler sign-and-trade', 'https://www.hoopsrumors.com/2019/07/heat-acquire-jimmy-butler-in-sign-and-trade.html', 'Hoops Rumors', 'reporting')
source('w3-markkanen21', 'Cleveland acquires Markkanen in three-team sign-and-trade', 'https://cdn-uat.nba.com/news/cavs-acquire-lauri-markkanen-from-bulls-in-3-team-trade')
source('w3-markkanen-conditions', 'Markkanen trade and Portland first-round protection schedule', 'https://www.espn.com/nba/story/_/id/32096028/sources-cleveland-cavaliers-get-lauri-markkanen-chicago-bulls-sign-trade-part-3-way-deal-portland-trail-blazers', 'ESPN', 'reporting')
source('w3-trades21', '2021 completed offseason trades: Markkanen pick terms', 'https://www.hoopsrumors.com/2021/07/2021-nba-offseason-trades.html', 'Hoops Rumors', 'reporting')
source('w3-mitchell17', 'Utah acquires Donovan Mitchell draft rights from Denver', 'https://cdn-uat.nba.com/news/utah-jazz-acquire-draft-rights-donovan-mitchell-denver')
source('w3-lewis24', 'New Orleans completes Kira Lewis trade with Indiana', 'https://www.nba.com/pelicans/news/new-orleans-pelicans-complete-trade-with-indiana-pacers')
source('w3-lewis24-terms', 'Kira Lewis first moves to Indiana in a separate completed exchange', 'https://www.hoopsrumors.com/2024/01/pelicans-trade-kira-lewis-jr-to-pacers.html', 'Hoops Rumors', 'reporting')
source('w3-lewis24-cash', 'Indiana reporting confirms Lewis cash consideration', 'https://www.si.com/nba/pacers/roster/pacers-acquire-kira-lewis-jr-second-round-draft-pick-trade-new-orleans-pelicans', 'Sports Illustrated / Tony East', 'reporting')
source('w3-siakam24', 'The completed Siakam exchange with Indiana', 'https://www.hoopsrumors.com/2024/01/raptors-trade-pascal-siakam-to-pacers-waive-christian-koloko.html', 'Hoops Rumors', 'reporting')
source('w3-trades24', '2023–24 completed in-season trades and pick conditions', 'https://www.hoopsrumors.com/2023/11/2023-24-in-season-nba-trades.html', 'Hoops Rumors', 'reporting')
source('w3-agbaji24', 'Toronto announces Olynyk and Agbaji acquisition', 'https://www.nba.com/raptors/news/raptors-acquire-olynyk-and-agbaji-from-jazz')
source('w3-agbaji24-pick', 'The Siakam first included with Lewis and Porter in Utah exchange', 'https://www.si.com/nba/2024/02/08/raptors-acquire-kelly-olynyk-four-player-trade-jazz', 'Sports Illustrated', 'reporting')
source('w3-ingram25', 'Toronto acquires Ingram from New Orleans', 'https://cdn-uat.nba.com/news/new-orleans-trades-brandon-ingram-to-toronto')
source('w3-ingram25-terms', '2025 deadline recap: Ingram and Fox pick conditions', 'https://www.hoopsrumors.com/2025/02/2025-nba-trade-deadline-recap.html', 'Hoops Rumors', 'reporting')
source('w3-sexton25', 'Charlotte announces Sexton acquisition on June 29', 'https://www.nba.com/hornets/news/charlotte-hornets-acquire-collin-sexton-from-utah')
source('w3-sexton25-terms', 'Sexton trade: Utah / Clippers most-favorable 2030 second', 'https://www.hoopsrumors.com/2025/06/jazz-to-trade-collin-sexton-to-hornets-for-jusuf-nurkic.html', 'Hoops Rumors', 'reporting')
source('w3-harden23', 'Clippers announce completed three-team Harden exchange', 'https://www.nba.com/clippers/news/clippers-acquire-10-time-nba-all-star-james-harden-and-p-j-tucker-in-three-team-deal')
source('w3-harden23-terms', 'Harden exchange: all three teams, pick pools, swaps and cash', 'https://www.hoopsrumors.com/2023/10/sixers-trading-james-harden-to-clippers.html', 'Hoops Rumors', 'reporting')
source('w3-jackson25', 'Washington acquires Jackson and the 2026 composite first', 'https://www.nba.com/wizards/news/washington-acquires-first-round-pick-from-philadelphia')
source('w3-harden26', 'Cleveland–Clippers final Harden and Garland exchange', 'https://www.hoopsrumors.com/2026/02/james-harden-headed-to-cavs-clippers-to-receive-darius-garland-second-rounder.html', 'Hoops Rumors', 'reporting')
source('w3-harden26-nba', 'NBA confirms Harden–Garland trade', 'https://cdn-uat.nba.com/news/james-harden-darius-garland-trade')
source('w3-fox25', 'San Antonio announces Fox and McLaughlin acquisition', 'https://www.nba.com/spurs/news/spurs-acquire-deaaron-fox-and-jordan-mclaughlin')
source('w3-fox25-terms', 'Final three-team Fox / LaVine exchange and conditional picks', 'https://www.hoopsrumors.com/2025/02/spurs-finalizing-trade-for-kings-deaaron-fox-lavine-heading-to-sacramento.html', 'Hoops Rumors', 'reporting')
source('w3-valanciunas25', 'Sacramento acquires Valančiūnas from Washington', 'https://www.nba.com/news/wizards-trade-jonas-valanciunas-to-kings')
source('w3-valanciunas25-picks', 'Valančiūnas exchange: Denver 2028 and Sacramento 2029 seconds', 'https://www.espn.co.uk/nba/story/_/id/43708106/kings-acquire-valanciunas-trade-wizards', 'ESPN', 'reporting')
source('w3-kings25-guide', 'Sacramento 2025–26 media guide: February 5 Valančiūnas acquisition', 'https://cdn.nba.com/teams/uploads/sites/1610612758/2025/10/2025-26-Sacramento-Kings-Media-Guide-copy.pdf', 'Sacramento Kings media guide')
source('w3-valanciunas-denver', 'Denver announces completed Valančiūnas–Šarić exchange', 'https://www.nba.com/nuggets/news/nuggets-acquire-jonas-valanciunas')
source('w3-summer25', 'Official 2025 offseason tracker: final July 13 Valančiūnas date', 'https://cdn-uat.nba.com/news/2025-offseason-trade-tracker')
source('w3-murray22', 'Atlanta completes Murray and Landale acquisition on June 30', 'https://atlantahawkspr.wordpress.com/wp-content/uploads/2022/06/6.30.22-spurs-trade.pdf', 'Atlanta Hawks media relations')
source('w3-murray22-terms', 'Murray exchange: Charlotte first and Atlanta unprotected rights', 'https://www.hoopsrumors.com/2022/06/spurs-to-trade-dejounte-murray-to-hawks.html', 'Hoops Rumors', 'reporting')
source('w3-olynyk25', 'San Antonio announces Olynyk acquisition', 'https://www.nba.com/spurs/news/spurs-aquire-kelly-olynyk')
source('w3-olynyk25-terms', 'Olynyk exchange: Dallas / Oklahoma City / Philadelphia 2026 second', 'https://www.hoopsrumors.com/2025/07/wizards-trading-kelly-olynyk-to-spurs.html', 'Hoops Rumors', 'reporting')
source('w3-draft24-order', '2024 draft order: Indiana No. 19 and Oklahoma City No. 29', 'https://www.hoopsrumors.com/2024/05/full-2024-nba-draft-order.html', 'Hoops Rumors', 'reporting')
source('w3-draft25-order', 'NBA Communications: 2025 final draft order and original franchises', 'https://pr.nba.com/2025-nba-draft-lottery-results/', 'NBA Communications')
source('w3-siakam24-protection', 'Siakam trade: first-round protections and fallback years', 'https://www.si.com/nba/pacers/news/sources-indiana-pacers-three-draft-picks-traded-to-toronto-raptors-are-protected', 'Sports Illustrated / Tony East', 'reporting')
source('w3-jackson25-crosscheck', 'Philadelphia reporting confirms Jared Butler and four seconds', 'https://sports.yahoo.com/sixers-pick-jared-butler-deal-105143586.html', 'NBC Sports Philadelphia via Yahoo Sports', 'reporting')
source('w3-raynaud25', 'Sacramento selects Maxime Raynaud at No. 42', 'https://www.nba.com/draft/2025/prospects/maxime-raynaud')

# Jimmy Butler's first three exchanges, with two genuinely shared outgoing branches.
tx('butler-minnesota','2017-06-22','Chicago starts over.','Butler and the No. 16 draft rights go to Minnesota. Chicago receives LaVine, Dunn and the rights to Markkanen at No. 7.','CHI MIN',ms('butler','CHI','MIN')+ms('patton','CHI','MIN','rights')+ms('lavine dunn','MIN','CHI')+ms('markkanen','MIN','CHI','rights'),'w3-butler17 w3-butler17-min',short='Butler joins Minnesota')
obligation('w3-butler22-second','2022 Philadelphia / Denver second',None,2022,2,conditions='More favorable of Philadelphia and Denver’s 2022 second-round picks. Subsequent conveyance is not traced.',candidates=['PHI','DEN'])
tx('butler-philadelphia','2018-11-12','Philadelphia makes its move.','Butler and Patton move together again. Covington, Šarić, Bayless and a conditional second-round entitlement form Minnesota’s return.','MIN PHI',ms('butler patton','MIN','PHI')+ms('covington saric bayless w3-butler22-second','PHI','MIN'),'w3-butler18 w3-butler18-second',notes=['November 12 is the completed trade date; November 10 was the reported agreement.'],short='Butler joins Philadelphia')
cash('w3-butler19-cash','$110,000 from the Clippers to Miami in the completed four-team exchange.')
tx('butler-miami','2019-07-06','Four teams make Miami possible.','Butler joins Miami through a sign-and-trade. Richardson goes to Philadelphia, while Portland and the Clippers make the complete exchange work.','PHI MIA POR LAC',[m('butler','PHI','MIA','player','Signed and traded by Philadelphia.')]+ms('richardson','MIA','PHI')+ms('leonard-meyers','POR','MIA')+ms('whiteside','MIA','POR')+ms('harkless','POR','LAC')+ms('lessort','PHI','LAC','rights')+ms('mia23','MIA','LAC')+ms('w3-butler19-cash','LAC','MIA'),'w3-butler19 w2-trades19',notes=['This is the completed four-team structure. Earlier proposals involving Dallas did not become this transaction. Miami’s first later joins the Paul George package; subsequent protection amendments are outside this route.'],short='Butler reaches Miami')
obligation('w3-por22-markkanen','Portland protected future first','POR',2022,conditions='Lottery protected in 2022 through 2028. If no first conveys, becomes Portland’s 2028 second. Later fulfillment is untraced.',protection=[dict(year=y,protectedRanges=[[1,14]]) for y in range(2022,2029)])
obligation('w3-den23-markkanen-second','Denver protected 2023 second','DEN',2023,2,conditions='Protected 31–46 in 2023; only positions 47–60 convey. Later disposition is not traced.',protection=[dict(year=2023,protectedRanges=[[31,46]])])
tx('markkanen-cleveland','2021-08-28','Markkanen’s next stop is Cleveland.','A three-team sign-and-trade brings Markkanen to the Cavaliers. Portland receives Nance; Chicago receives Jones and two conditional draft assets.','CHI CLE POR',[m('markkanen','CHI','CLE','player','Signed and traded by Chicago.')]+ms('nance','CLE','POR')+ms('jones-derrick w3-por22-markkanen','POR','CHI')+ms('w3-den23-markkanen-second','CLE','CHI'),'w3-markkanen21 w3-markkanen-conditions w3-trades21',short='Markkanen joins Cleveland')
tx('mitchell-utah','2017-06-22','Utah finds Mitchell at thirteen.','Denver’s selection becomes Utah’s new guard. The Jazz send Lyles and the No. 24 rights to Lydon in the same draft-night package.','DEN UTA',ms('mitchell-donovan','DEN','UTA','rights')+ms('lyles','UTA','DEN')+ms('lydon','UTA','DEN','rights'),'w3-mitchell17',short='Mitchell’s draft-night arrival')

# Siakam: two January 17 transactions, then reuse the acquired package accurately.
obligation('w3-lewis24-second','2024 New Orleans / Chicago second',None,2024,2,conditions='Least favorable of New Orleans and Chicago’s 2024 second-round picks. Later selection and onward transfers are untraced.',candidates=['NOP','CHI'])
cash('w3-lewis24-cash','$110,000 paid by Indiana to New Orleans.')
tx('lewis-indiana','2024-01-17','A short stop in Indiana.','Indiana acquires Lewis and a second-round entitlement before completing the Siakam trade. His contract can then join Indiana’s outgoing package.','NOP IND',ms('lewis-kira w3-lewis24-second','NOP','IND')+ms('w3-lewis24-cash','IND','NOP'),'w3-lewis24 w3-lewis24-terms w3-lewis24-cash',notes=['Completed separately before the Toronto exchange. The second stays with Indiana; it is not sent to Toronto.'],order=-1,short='Lewis passes through Indiana')
obligation('w3-ind24-siakam','Indiana protected 2024 first','IND',2024,conditions='Top 3 protected in 2024. If retained, Toronto receives second-round picks in 2024 and 2025; the original franchises of that unused fallback are not asserted. Conveyance is revealed at the draft.',protection=[dict(year=2024,protectedRanges=[[1,3]])])
obligation('w3-siakam24-composite','2024 least-favorable first',None,2024,conditions='Least favorable of the eligible Oklahoma City, Clippers, Houston (top 4 protected) and Utah (top 10 protected) firsts in 2024. One selection, not four.',candidates=['OKC','LAC','HOU','UTA'])
obligation('w3-ind26-siakam','Indiana protected 2026 first','IND',2026,conditions='Top 4 protected in 2026 and 2027. If neither first conveys, becomes second-round picks in 2027 and 2028; the original franchises of that unused fallback are not asserted. Later transfers and fulfillment are untraced.',protection=[dict(year=y,protectedRanges=[[1,4]]) for y in (2026,2027)])
tx('siakam-indiana','2024-01-17','Indiana adds Siakam.','Three players and three first-round entitlements go to Toronto. Two of those entitlements soon leave distinct traces: a draft selection and another trade package.','IND TOR',ms('siakam','TOR','IND')+ms('brown-bruce lewis-kira nwora w3-ind24-siakam w3-siakam24-composite w3-ind26-siakam','IND','TOR'),'w3-siakam24 w3-trades24 pacers25-guide w3-siakam24-protection',notes=['Lewis had just been acquired from New Orleans in a separate transaction. The 2024 composite first is one entitlement drawn from a protected comparison pool.'],short='Siakam joins Indiana')
tx('agbaji-toronto','2024-02-08','Toronto spends one of the firsts.','The composite pick from the Siakam return joins Lewis and Porter in a new package. Toronto acquires Olynyk and Agbaji together.','TOR UTA',ms('olynyk agbaji','UTA','TOR')+ms('lewis-kira porter-otto w3-siakam24-composite','TOR','UTA'),'w3-agbaji24 w3-agbaji24-pick w3-trades24',short='Olynyk and Agbaji reach Toronto')
selection('walter-draft','2024-06-26','TOR','w3-ind24-siakam','walter','Ja’Kobe Walter',19,2024,'IND',1,'w2-draft24 w3-siakam24 w3-draft24-order','Indiana’s own first conveys at No. 19. Toronto selects Ja’Kobe Walter.')
selection('collier-draft','2024-06-26','UTA','w3-siakam24-composite','collier','Isaiah Collier',29,2024,'OKC',1,'w2-draft24 w3-agbaji24-pick w3-draft24-order','Oklahoma City’s No. 29 satisfies the composite entitlement. Utah selects Isaiah Collier after acquiring the right from Toronto.')
obligation('w3-tor31-ingram-second','Toronto 2031 second','TOR',2031,2)
tx('ingram-toronto','2025-02-06','Two branches become another package.','Brown and the Indiana first came from the Siakam deal. Olynyk arrived through the next exchange. Toronto combines them with a second-round pick for Ingram.','TOR NOP',ms('ingram','NOP','TOR')+ms('brown-bruce olynyk w3-ind26-siakam w3-tor31-ingram-second','TOR','NOP'),'w3-ingram25 w3-ingram25-terms',short='Ingram joins Toronto')
obligation('w3-sexton30-second','2030 Utah / Clippers second',None,2030,2,conditions='Most favorable of Utah and the Clippers’ 2030 second-round picks. Subsequent use is untraced.',candidates=['UTA','LAC'])
tx('sexton-charlotte','2025-06-29','Sexton’s branch reaches Charlotte.','One player from Cleveland’s Mitchell package moves again. Utah pairs Sexton with a second-round entitlement to acquire Nurkić.','UTA CHA',ms('sexton w3-sexton30-second','UTA','CHA')+ms('nurkic','CHA','UTA'),'w3-sexton25 w3-sexton25-terms',notes=['Charlotte’s dated announcement and the completed-trade report establish June 29 in the United States. Some league summaries label the transaction June 30. Nurkić’s earlier acquisition by Charlotte and Sexton’s later career are outside this route.'],short='Sexton joins Charlotte')

# Harden's three-team Clippers exchange, its first-round tail, and Cleveland endpoint.
obligation('w3-lac28-harden','Clippers 2028 first','LAC',2028)
swap('w3-lac29-harden-swap','LAC',2029,'Philadelphia may exchange its 2029 first for the Clippers’ first, protected for Clippers selections 1–3. The right is not an additional outright pick; exercise is untraced.')
obligation('w3-harden24-second','2024 conditional composite second',None,2024,2,conditions='Most favorable of Toronto, Indiana, Utah and Cleveland’s 2024 seconds, unless that best pick is Utah or Cleveland; in that case, the second most favorable of the four conveys. Later selection is untraced.',candidates=['TOR','IND','UTA','CLE'])
obligation('w3-lac29-harden-second','Clippers 2029 second','LAC',2029,2)
swap('w3-lac27-harden-swap','LAC',2027,'Oklahoma City can exchange its own 2027 first or the Denver first it controls (Denver protected 1–5) for the Clippers’ unprotected 2027 first. This is one swap right, not ownership of every pick in the comparison.')
cash('w3-harden23-phi-cash','$2 million from the Clippers to Philadelphia.')
cash('w3-harden23-okc-cash','$1.1 million from the Clippers to Oklahoma City.')
# Same composite entitlement later sent by Washington to Dallas; refine the existing
# condition with the now-verified Houston eligibility restriction, without replacing identity.
assets['ad26-first']['conditions']='Least favorable of the eligible Oklahoma City, Clippers and Houston 2026 firsts; Houston is top 4 protected. Later fulfillment is untraced; no draft selection is assigned.'
assets['ad26-first']['candidates']=['OKC','LAC','HOU']
assets['ad26-first']['origin']=None
tx('harden-clippers','2023-11-01','A third team supplies the second first.','Harden heads to Los Angeles with Tucker and Petrušev. Oklahoma City helps complete Philadelphia’s return by supplying a 2026 first-round entitlement.','PHI LAC OKC',ms('harden tucker petrusev','PHI','LAC')+ms('morris-marcus batum covington kj-martin w3-lac28-harden w3-lac29-harden-swap w3-harden24-second w3-lac29-harden-second w3-harden23-phi-cash','LAC','PHI')+ms('ad26-first','OKC','PHI')+ms('w3-lac27-harden-swap w3-harden23-okc-cash','LAC','OKC'),'w3-harden23 w3-harden23-terms',notes=['November 1 is the completed three-team exchange, following October 31 reports. Players, two outright first-round entitlements, separate swaps, seconds and cash remain one package.'],short='Harden joins the Clippers')
obligation('w3-gsw-phx27-jackson','2027 Golden State / Phoenix second',None,2027,2,conditions='Most favorable of Golden State and Phoenix’s 2027 seconds. A composite entitlement, not both original obligations.',candidates=['GSW','PHX'])
obligation('w3-gsw28-jackson','Golden State 2028 second','GSW',2028,2)
obligation('w3-phx-por30-jackson','2030 Phoenix / Portland second',None,2030,2,conditions='Most favorable of Phoenix and Portland’s 2030 seconds. A composite entitlement, not both original obligations.',candidates=['PHX','POR'])
obligation('w3-was30-jackson','Washington 2030 second','WAS',2030,2)
tx('jackson-washington','2025-02-06','The Harden first changes hands.','Philadelphia sends the same 2026 entitlement with Jackson to Washington. Its return is Jared Butler and four second-round entitlements.','PHI WAS',ms('jackson-reggie ad26-first','PHI','WAS')+ms('butler-jared w3-gsw-phx27-jackson w3-gsw28-jackson w3-phx-por30-jackson w3-was30-jackson','WAS','PHI'),'w3-jackson25 w3-jackson25-crosscheck',notes=['This records the final completed package, including Jared Butler and all four seconds. Earlier cash-only summaries are incomplete.'],short='Washington acquires the first')
obligation('w3-cle26-harden-second','Cleveland 2026 second','CLE',2026,2)
tx('harden-cleveland','2026-02-04','Harden’s route reaches Cleveland.','The Cavaliers exchange Garland and their 2026 second for Harden. This is a separate branch from the first-round entitlement still moving through other deals.','LAC CLE',ms('harden','LAC','CLE')+ms('garland w3-cle26-harden-second','CLE','LAC'),'w3-harden26 w3-harden26-nba tracker26',short='Harden joins Cleveland')

# Fox / LaVine: track both players and the actual pre-existing pick obligations.
for year in (2025,2027): obligation(f'w3-atl{year}-murray',f'Atlanta {year} first','ATL',year)
swap('w3-atl26-murray-swap','ATL',2026,'San Antonio may exchange its 2026 first for Atlanta’s unprotected first. Later subordinate rights and exercise are outside this branch.')
tx('murray-atlanta','2022-06-30','Atlanta’s Charlotte right heads to San Antonio.','Murray and Landale go to Atlanta. San Antonio receives Gallinari, the Charlotte obligation and Atlanta’s own future firsts and swap.','SAS ATL',ms('murray-dejounte landale','SAS','ATL')+ms('gallinari cha22-reddish w3-atl2025-murray w3-atl2027-murray w3-atl26-murray-swap','ATL','SAS'),'w3-murray22 w3-murray22-terms',short='Murray joins Atlanta')
obligation('w3-chi25-fox-first','Chicago first obligation returned','CHI',2025,conditions='Chicago regains its own conditional first-round obligation from San Antonio, protected 1–10 in 2025. This returns the outstanding claim to its issuer; it is not an extra first-round selection. The prior DeRozan transaction and unused rollover terms are outside this route.',protection=[dict(year=2025,protectedRanges=[[1,10]])])
obligation('w3-sas27-fox-first','San Antonio 2027 first','SAS',2027)
obligation('w3-chi25-fox-second','Chicago 2025 second','CHI',2025,2)
obligation('w3-den28-fox-second','Denver protected 2028 second','DEN',2028,2,conditions='Protected 31–33 in 2028. Only positions 34–60 convey; no later substitute is asserted.',protection=[dict(year=2028,protectedRanges=[[31,33]])])
obligation('w3-sac28-fox-second','Sacramento 2028 second returned','SAC',2028,2,conditions='Sacramento’s own 2028 second-round right returns from Chicago. This does not create an additional second-round selection.')
tx('fox-san-antonio','2025-02-03','Three teams redraw their backcourts.','Fox and McLaughlin go to San Antonio. Sacramento receives LaVine, Cissoko and draft assets; Chicago receives three players and its own first-round obligation back.','SAC SAS CHI',ms('fox mclaughlin-jordan','SAC','SAS')+ms('huerter','SAC','CHI')+ms('lavine w3-sac28-fox-second','CHI','SAC')+ms('collins-zach jones-tre w3-chi25-fox-first','SAS','CHI')+ms('cissoko cha22-reddish w3-sas27-fox-first min31 w3-chi25-fox-second w3-den28-fox-second','SAS','SAC'),'w3-fox25 w3-fox25-terms',notes=['Finalized February 3, following February 2 reports. Charlotte’s first remains lottery protected in 2025 with the already-documented second-round fallback. Minnesota’s 2031 first is the same right from the Dillingham draft-night trade. Returned own picks are not additional draft slots.'],short='Fox and LaVine change teams',resolutions=[dict(asset='w3-chi25-fox-first',status='extinguished',detail='San Antonio’s conditional claim is cancelled when Chicago reacquires its own first-round obligation.')])
tx('valanciunas-sacramento','2025-02-05','Sacramento repackages part of the return.','Cissoko and the Denver second from the Fox exchange join Sacramento’s 2029 second. Washington sends Valančiūnas in return.','SAC WAS',ms('valanciunas','WAS','SAC')+ms('cissoko w3-den28-fox-second sac29-cj-second','SAC','WAS'),'w3-valanciunas25 w3-valanciunas25-picks w3-kings25-guide',notes=['The Kings media guide dates completion February 5. The Denver pick conveys only at positions 34–60.'],short='Valančiūnas joins Sacramento')
tx('valanciunas-denver','2025-07-13','Denver and Sacramento exchange centers.','Valančiūnas moves to Denver for Šarić. The final exchange includes no additional draft consideration.','SAC DEN',ms('valanciunas','SAC','DEN')+ms('saric','DEN','SAC'),'w3-valanciunas-denver w3-summer25',notes=['July 13 is the official completed-trade date. July 1 was the reported agreement. Šarić’s intervening career after Minnesota is outside this route.'],short='Valančiūnas joins Denver')
selection('raynaud-draft','2025-06-26','SAC','w3-chi25-fox-second','raynaud','Maxime Raynaud',42,2025,'CHI',2,'w3-raynaud25 w3-fox25-terms w3-draft25-order','The Chicago second acquired in the Fox exchange conveys at No. 42. Sacramento selects Maxime Raynaud.')
obligation('w3-olynyk26-second','2026 Dallas / Thunder / Sixers second',None,2026,2,conditions='Least favorable of Dallas, Oklahoma City and Philadelphia’s 2026 second-round selections. Actual fulfillment is outside this route.',candidates=['DAL','OKC','PHI'])
tx('olynyk-san-antonio','2025-07-09','Olynyk takes one more turn.','Washington sends Olynyk to San Antonio for Branham, Wesley and a composite second-round entitlement. Both guards belong to the same outgoing package.','WAS SAS',ms('olynyk','WAS','SAS')+ms('branham wesley w3-olynyk26-second','SAS','WAS'),'w3-olynyk25 w3-olynyk25-terms',short='Olynyk joins San Antonio')

story('harden-clippers','Harden, again.','One star. Another city. A first still moving.','Follow Harden to Los Angeles and Cleveland, then follow a different part of the return all the way to Dallas.','Modern',2023,2026,'LAC','#929ee8','harden-philadelphia harden-clippers jackson-washington harden-cleveland davis-wizards','harden-clippers','The 2022 Philadelphia arrival, final 2023 three-team Clippers exchange, the 2025 transfer of its composite first and two separate February 2026 endpoints. Later selection, swap exercise and other outgoing-player careers are untraced.','The 2026 first that Philadelphia received for Harden later joins Washington’s Anthony Davis package. Harden himself takes a different route.')
story('mitchell','The Mitchell exchange.','One arrival. Three paths out.','Cleveland’s big swing connects a draft-night gamble, Chicago’s rebuild and the next moves in Utah.','Modern',2022,2025,'CLE','#e6a577','mitchell-utah butler-minnesota markkanen-cleveland mitchell-cleveland agbaji-toronto collier-draft sexton-charlotte','mitchell-cleveland','Mitchell’s 2017 draft-rights arrival, Markkanen’s Chicago and Cleveland moves, the complete 2022 Cleveland–Utah exchange, Agbaji’s Toronto package and Sexton’s 2025 Charlotte trade. Utah’s later first-round pools and actual swap exercise are untraced.','Cleveland acquires one star in a package. Utah’s player branches later reach Toronto and Charlotte, each through a separate complete exchange.')
story('fox-lavine','Fox. LaVine. The next move.','Three backcourts change in one night.','Follow the February 2025 exchange backward through its picks and forward to Sacramento’s next center.','Modern',2025,2025,'SAC','#b49ae1','butler-minnesota reddish-new-york murray-atlanta dillingham-minnesota fox-san-antonio valanciunas-sacramento raynaud-draft valanciunas-denver','fox-san-antonio','The final Fox–LaVine three-team exchange, selected prior LaVine and pick transfers, the complete Valančiūnas packages, and Chicago’s second-round conveyance as Raynaud. Charlotte’s eventual fallback and other first-round fulfillment remain untraced.','Two rights acquired in earlier San Antonio deals join the Fox exchange. Sacramento then combines two incoming pieces with another pick for Valančiūnas.')
story('siakam','Siakam’s second act.','Toronto’s return keeps moving.','A first becomes Walter. Another helps acquire Olynyk and Agbaji. A later package brings Ingram north.','Modern',2024,2026,'TOR','#f07c91','lewis-indiana siakam-indiana agbaji-toronto walter-draft collier-draft ingram-toronto mccollum-washington olynyk-san-antonio trae-wizards davis-wizards','siakam-indiana','The two separate January 2024 trades, both 2024 first-round conveyances, Ingram’s complete 2025 package, and selected Olynyk/McCollum/Branham moves through February 2026. The Indiana first’s later transfers and fulfillment are untraced.','Toronto reuses different pieces of the Siakam return in different packages. Those packages connect Toronto, Utah, New Orleans, Washington and San Antonio.')
story('butler-journey','Before Miami, a fork.','Butler goes one way. LaVine and Markkanen another.','The 2017 Chicago rebuild has branches that meet the 2022 Mitchell and 2025 Fox trades.','Modern',2017,2025,'CHI','#ee8493','butler-minnesota butler-philadelphia butler-miami markkanen-cleveland mitchell-cleveland fox-san-antonio sexton-charlotte','butler-minnesota','Butler’s complete 2017, 2018 and 2019 trades, plus the LaVine and Markkanen branches into Fox and Mitchell packages. Butler’s own path stops at Miami in 2019; his separate 2025 Warriors story is available in the wider web. Remaining outgoing-player careers and pick resolutions are untraced.','The player Chicago sends away and the players it receives continue through independent packages. Neither branch alone explains the other’s outcomes.')
