"""Classic wave 3. Execute AFTER the existing expansions in curate.py's globals.
Research only; no network access, file writes, app changes or third-party prose.
Requires AssetKind 'consideration' for one explicitly undisclosed consideration.
"""

source('c3-bucks08','Milwaukee Bucks 2008 media guide: 1975 and 1984 transaction ledger','https://nyc3.digitaloceanspaces.com/sportsarchive-documents/prod/698bdc3c08deb/2008_Media_Guide.pdf','Milwaukee Bucks media guide')
source('c3-kareem-rights','Milwaukee confirms the two 1975 rookies were draft rights','https://www.nba.com/bucks/features/mb-140306-kareem-abdul-jabbar-start-of-a-renaissance')
source('c3-kareem-cash','The Kareem trade documents include $800,000','https://www.latimes.com/archives/la-xpm-1987-12-25-sp-21142-story.html','Los Angeles Times','reporting')
source('c3-lakers79','Los Angeles Lakers 1979 media guide: Kareem acquisition','https://library.sfo2.cdn.digitaloceanspaces.com/publications/basketball/yearbooks/KLALAMG-1979.pdf','Los Angeles Lakers media guide')
source('c3-bulls22','Chicago Bulls 2022–23 media guide: 1987 draft-night trade','https://chibullsdigital.com/mediaGuide/2022_ChicagoBulls_MG_NBA_HI.pdf','Chicago Bulls media guide')
source('c3-pippen87','Seattle’s Pippen trade and the extra draft considerations','https://www.spokesman.com/stories/2020/apr/27/yes-the-sonics-traded-scottie-pippen-for-olden-pol/','Seattle Times / Spokesman-Review','reporting')
source('c3-pippen87-protection','Contemporary draft report: Pippen trade protection','https://www.latimes.com/archives/la-xpm-1987-06-23-sp-10130-story.html','Los Angeles Times','reporting')
source('c3-pippen99-completed','January 22 completed Pippen sign-and-trade','https://www.washingtonpost.com/archive/sports/1999/01/23/nba-transactions/b6fb8ebb-9e59-4ec4-9363-ba8ea0e68bc2/','Washington Post','reporting')
source('c3-pippen99-conflict','Pippen’s later pick outcome reported as a 2000 second','https://www.houstonpress.com/news/westbrook-latest-former-franchise-icon-to-become-a-rocket-11323229/','Houston Press','reporting')
source('c3-blazers23','Portland 2022–23 media guide: Cato and Pippen trade packages','https://www.ripcityresource.com/pdf/mediaguide/2022-23_TrailBlazers_MediaGuide.pdf','Portland Trail Blazers media guide')
source('c3-pippen99-portland','Completed seven-player Pippen exchange','https://assets.espn.go.com/nba/news/1999/1001/90487.html','Associated Press / ESPN','reporting')
source('c3-spurs96','San Antonio 1996 media guide: Rodman acquisition and departure','https://library.sfo2.cdn.digitaloceanspaces.com/publications/basketball/yearbooks/KSASPMG-1996.pdf','San Antonio Spurs media guide')
source('c3-spurs02','San Antonio 2002 media guide: Elliott’s return on July 19, 1994','https://library.sfo2.cdn.digitaloceanspaces.com/publications/basketball/yearbooks/KSASPMG-2002.pdf','San Antonio Spurs media guide')
source('c3-rodman93','Rodman trade and the separate Isaiah Morris consideration','https://www.deseret.com/1993/10/2/19068856/the-worm-turns-to-spurs-deal-finally-done/','Associated Press / Deseret News','reporting')
source('c3-rodman93-protection','Rodman trade: 1994–96 swap protection','https://www.latimes.com/archives/la-xpm-1993-10-02-sp-41479-story.html','Los Angeles Times','reporting')
source('c3-rodman93-picks','San Antonio’s transaction history retains the Detroit second','https://www.expressnews.com/spurs-nation/article/Spurs-trade-history-includes-several-blockbusters-12946665.php','San Antonio Express-News','reporting')
source('c3-elliott94','Elliott reacquisition completed July 19','https://www.upi.com/Archives/1994/07/19/Spurs-acquire-Sean-Elliott/1839774590400/','United Press International','reporting')
source('c3-rodman95','Chicago acquires Rodman for Perdue and other considerations','https://www.upi.com/Archives/1995/10/02/Bulls-Acquire-Rodman/6237812606400/','United Press International','reporting')
source('c3-rodman95-undisclosed','Neither team disclosed the additional Rodman consideration','https://www.sfgate.com/sports/article/NBA-NOTES-Bulls-Acquire-Enigmatic-Rodman-3022641.php','San Francisco Chronicle / wire reports','reporting')
source('c3-iverson06','Denver completes the Iverson trade','https://www.nba.com/nuggets/news/nuggets_acquire_iverson_121906.html')
source('c3-iverson-pick-origins','Philadelphia identifies Denver and Dallas as pick origins','https://www.espn.com/nba/news/story?id=2702501','ESPN','reporting')
source('c3-sixers24','Philadelphia 2023–24 media guide: 2007 draft and trades','https://cdn.nba.com/teams/uploads/sites/1610612755/2024/01/23-24-76ers-Media-Guide-Update-compressed.pdf','Philadelphia 76ers media guide')
source('c3-heat24','Miami 2023–24 media guide: Cook, Smith and the 2010 exchange','https://cdn.nba.com/teams/uploads/sites/1610612748/2023/11/2023-24-Miami-Heat-Media-Guide_39884007.pdf','Miami Heat media guide')
source('c3-draft10-order','NBA 2010 draft order identifies Miami No. 18 and Minnesota No. 32','https://pr.nba.com/2009-10-ties-broken/','NBA Communications')
source('c3-iverson08','Detroit announces the Iverson–Billups package','https://www.nba.com/pistons/news/iverson_081103.html')
source('c3-magic23','Orlando 2022–23 media guide: McGrady and Francis transactions','https://cdn.nba.com/teams/uploads/sites/1610612753/2022/11/orlando-magic-media-guide-2022-23.pdf','Orlando Magic media guide')
source('c3-ariza07','Lakers announce Ariza acquisition','https://www.nba.com/lakers/news/071120_lakersacquireariza.html')
source('c3-mcgrady10-terms','McGrady trade: the protected first and separate swap','https://www.si.com/more-sports/2010/02/18/mcgrady-trade','Sports Illustrated','reporting')
source('c3-mcgrady10-protection','Four years of top-five protection on New York’s first','https://www.shamsports.com/2010/02/the-finances-of-trade-deadline-deals.html','Mark Deeks / ShamSports','reporting')
source('c3-odom11-terms','Larry Coon documents the Odom first and second-round swap','https://www.espn.co.uk/blog/los-angeles/lakers/post/_/id/35622/assessing-the-lakers-second-round-and-future-picks','ESPN / Larry Coon','reporting')
source('c3-hill12','Lakers acquire Jordan Hill for Fisher and the Dallas first','https://www.nba.com/lakers/news/lakers_acquire_jordan_hill_2012_03_15.html')
source('c3-djo12','Lakers 2022–23 media guide: acquiring Johnson-Odom’s rights','https://lalweb.blob.core.windows.net/public/lakers/media-relations/2022-23-Lakers-Media-Guide.pdf','Los Angeles Lakers media guide')
source('c3-mcgrady10-final','NBA completed deadline history: final McGrady package','https://cdn-uat.nba.com/news/trade-deadline-deals-all-time-history')
source('c3-mcgrady-pick-outcome','McGrady package’s protected first became the 2012 No. 16 pick','https://www.shamsports.com/player-profile?pid=881','Mark Deeks / ShamSports','reporting')

for _id,_name in [
 ('kareem','Kareem Abdul-Jabbar'),('wesley-walt','Walt Wesley'),('smith-elmore','Elmore Smith'),('winters','Brian Winters'),('meyers','Dave Meyers'),('bridgeman','Junior Bridgeman'),
 ('cummings','Terry Cummings'),('hodges','Craig Hodges'),('pierce-ricky','Ricky Pierce'),('johnson-marques','Marques Johnson'),('catchings','Harvey Catchings'),
 ('pippen','Scottie Pippen'),('polynice','Olden Polynice'),('rogers-roy','Roy Rogers'),('augmon','Stacey Augmon'),('cato','Kelvin Cato'),('gray-ed','Ed Gray'),('rogers-carlos','Carlos Rogers'),('shaw-brian','Brian Shaw'),('williams-walt','Walt Williams'),('anstey','Chris Anstey'),
 ('rodman','Dennis Rodman'),('morris-isaiah','Isaiah Morris'),('elliott-sean','Sean Elliott'),('wood-david','David Wood'),('curley','Bill Curley'),('perdue','Will Perdue'),
 ('iverson','Allen Iverson'),('mcfarlin','Ivan McFarlin'),('miller-andre','Andre Miller'),('smith-joe','Joe Smith'),('mcdyess','Antonio McDyess'),('samb','Cheikh Samb'),('smith-jason','Jason Smith'),
 ('mcgrady','Tracy McGrady'),('howard-juwan','Juwan Howard'),('lue','Tyronn Lue'),('gaines','Reece Gaines'),('francis','Steve Francis'),('mobley-cuttino','Cuttino Mobley'),('ariza','Trevor Ariza'),('hardaway-anfernee','Anfernee Hardaway'),('cook-brian','Brian Cook'),('evans-maurice','Maurice Evans'),
 ('hill-jordan','Jordan Hill'),('jeffries-jared','Jared Jeffries'),('landry-carl','Carl Landry'),('dorsey','Joey Dorsey'),('hughes','Larry Hughes'),('armstrong-hilton','Hilton Armstrong'),('rodriguez-sergio','Sergio Rodríguez'),('fisher','Derek Fisher'),('johnson-odom','Darius Johnson-Odom')]:
 if _id not in assets:player(_id,_name)

# One franchise identity; Seattle is the name applicable to Pippen's draft night.
if not any(a['name']=='Seattle SuperSonics' for a in teams['OKC'].get('aliases',[])):
 teams['OKC']['aliases']=teams['OKC'].get('aliases',[])+[dict(from_='1967-01-01',to='2008-06-30',name='Seattle SuperSonics')]

cash('c3-kareem75-cash','$800,000 paid by Los Angeles to Milwaukee, documented in the contemporary trade contract review.')
tx('kareem-lakers','1975-06-16','A skyhook changes coast.','Milwaukee sends Abdul-Jabbar and Wesley to Los Angeles. Two veterans, two sets of rookie rights and cash form the return.','MIL LAL',ms('kareem wesley-walt','MIL','LAL')+ms('smith-elmore winters c3-kareem75-cash','LAL','MIL')+ms('meyers bridgeman','LAL','MIL','rights'),'c3-bucks08 c3-kareem-rights c3-kareem-cash c3-lakers79',short='Kareem goes to Los Angeles')
cash('c3-cummings84-cash','Milwaukee sent cash with its three players. The media guide does not disclose the amount.')
tx('cummings-milwaukee','1984-09-29','Follow the rookie in the return.','Nine years later, Bridgeman joins Johnson and Catchings in a Clippers package. Cummings, Hodges and Pierce head to Milwaukee.','MIL LAC',ms('bridgeman johnson-marques catchings c3-cummings84-cash','MIL','LAC')+ms('cummings hodges pierce-ricky','LAC','MIL'),'c3-bucks08',notes=['The Clippers had relocated to Los Angeles by this transaction. Later Cummings trades are outside this bounded route.'],short='Bridgeman joins the Cummings package')

# A swap is not two outright first-round picks. Untraced fine print stays explicit.
obligation('c3-pippen87-second','1988 / 1989 second-round consideration',None,1988,2,conditions='A second-round choice in 1988 or 1989. The available completed-trade history does not establish the originating franchise and election mechanism sufficiently to assign a selection; this branch is untraced.')
swap('c3-pippen87-swap','CHI',1988,'Seattle could exchange firsts with Chicago in 1988 or 1989, excluding a top-three Chicago selection. The Bulls historical summary records the 1989 option; this branch does not assign the later exchanged picks.')
assets['c3-pippen87-swap']['name']='1988 / 1989 Chicago swap right'
tx('pippen-chicago','1987-06-22','Five and eight change hands.','Seattle sends Pippen’s draft rights to Chicago. Polynice’s rights, a second-round obligation and a protected first-round swap go the other way.','CHI OKC',ms('pippen','OKC','CHI','rights')+ms('polynice','CHI','OKC','rights')+ms('c3-pippen87-second c3-pippen87-swap','CHI','OKC'),'c3-bulls22 c3-pippen87 c3-pippen87-protection',notes=['Pippen was selected fifth and Polynice eighth. This records the completed draft-night rights exchange, not the pre-draft agreement.','The future second and swap are retained separately. Their later transfers and selections are outside the published route.'],short='Pippen’s rights go to Chicago')
cash('c3-cato97-cash','Portland also sent monetary considerations; no amount is stated in the cited team history.')
tx('cato-portland','1997-06-25','A Dallas draft choice enters the trail.','Dallas trades Cato’s draft rights to Portland for Anstey’s rights and cash. Cato will later travel in two star-sized packages.','DAL POR',ms('cato','DAL','POR','rights')+ms('anstey','POR','DAL','rights')+ms('c3-cato97-cash','POR','DAL'),'c3-blazers23 dx-dallas25',short='Dallas sends Cato’s rights to Portland')
obligation('c3-pippen99-second','Future second: year not reconciled',None,1999,2,conditions='Houston conveyed a future second-round consideration with Roy Rogers. The contemporary completed report and Rockets ledger call it a 1999 second; later reporting identifies a 2000 second. The conditional mechanism and origin are not established here. No draft outcome is assigned.')
tx('pippen-houston','1999-01-22','Chicago’s chapter closes.','The Bulls sign and trade Pippen to Houston. Rogers and a future second-round consideration come to Chicago.','CHI HOU',ms('pippen','CHI','HOU')+ms('rogers-roy c3-pippen99-second','HOU','CHI'),'harden-guide c3-pippen99-completed c3-pippen99-conflict',notes=['Pippen was signed and traded. The transaction date follows the completed January 22 report and Houston’s ledger.','Sources disagree about the second-round consideration’s year. Its existence is documented; its origin, conditional mechanism and eventual selection remain untraced.'],short='Pippen goes to Houston')
tx('pippen-portland','1999-10-02','Six players go the other way.','Houston trades Pippen to Portland. Its return includes Cato, the former Dallas draft choice, alongside five teammates.','HOU POR',ms('pippen','HOU','POR')+ms('augmon cato gray-ed rogers-carlos shaw-brian williams-walt','POR','HOU'),'c3-blazers23 c3-pippen99-portland harden-guide',short='Pippen goes to Portland')

swap('c3-det94-rodman-swap','DET',1994,'San Antonio may exchange firsts: top 10 protected in 1994, top 8 in 1995, unprotected in 1996.')
assets['c3-det94-rodman-swap']['protection']=[dict(year=1994,protectedRanges=[[1,10]]),dict(year=1995,protectedRanges=[[1,8]]),dict(year=1996,protectedRanges=[])]
obligation('c3-det94-rodman-second','Detroit 1994 second-round consideration','DET',1994,2,conditions='Detroit’s 1994 second-round consideration is included in the documented return. The original conditional trigger is not confirmed by the accessible sources; its subsequent trade and selection are untraced.')
tx('rodman-san-antonio','1993-10-01','Detroit and San Antonio exchange forwards.','Rodman goes to the Spurs. Elliott and Wood go to Detroit, while San Antonio also receives draft consideration with a protected swap.','DET SAS',ms('rodman c3-det94-rodman-swap c3-det94-rodman-second','DET','SAS')+ms('elliott-sean wood-david','SAS','DET'),'c3-spurs96 c3-rodman93 c3-rodman93-protection c3-rodman93-picks',notes=['The companion Isaiah Morris exchange is recorded separately, following the contemporaneous Associated Press account. Later team summaries combine the two same-day exchanges.','The 1994 second’s original conditional trigger is unconfirmed here. The protected swap’s possible 1994–96 years are not represented as three different first-round assets.'],short='Rodman goes to San Antonio')
obligation('c3-sas97-morris-second','Conditional 1997 second: Morris deal','SAS',1997,2,conditions='A conditional 1997 second-round consideration in the separate Isaiah Morris exchange. The published report does not disclose its trigger. No conveyance or expiration is asserted.')
tx('morris-san-antonio','1993-10-01','A separate exchange on the same day.','Detroit sends Morris to San Antonio for a conditional second. It accompanies the Rodman news, but has its own consideration.','DET SAS',ms('morris-isaiah','DET','SAS')+ms('c3-sas97-morris-second','SAS','DET'),'c3-rodman93',order=1,short='The Isaiah Morris companion trade')
obligation('c3-sas97-elliott-second','1997 second: Elliott return','SAS',1997,2,conditions='A 1997 San Antonio second-round consideration sent with Bill Curley’s rights for Sean Elliott. The cited completed report does not disclose additional conditions. It is not assumed identical to the earlier Morris conditional obligation; both contracts’ relationship is untraced.')
tx('elliott-san-antonio','1994-07-19','Elliott returns before Rodman leaves.','Detroit sends Elliott back to San Antonio. The Spurs send Curley’s draft rights and a 1997 second-round consideration.','DET SAS',ms('elliott-sean','DET','SAS')+ms('curley','SAS','DET','rights')+ms('c3-sas97-elliott-second','SAS','DET'),'c3-spurs02 c3-elliott94',notes=['The completed July 19 report and later Spurs transaction ledger are used. An earlier guide’s player biography lists July 18. The canceled February 1994 Houston proposal is not a completed trade and creates no edge.'],short='Sean Elliott goes back to San Antonio')
assets['c3-rodman95-other']=dict(id='c3-rodman95-other',name='Undisclosed additional consideration',kind='consideration',detail='Chicago sent additional consideration to San Antonio. The Spurs’ guide and contemporary UPI report confirm its existence; neither team disclosed its nature in the cited contemporary report. It is not labeled cash or assigned an invented value.')
tx('rodman-chicago','1995-10-02','The Worm changes sides.','Chicago acquires Rodman from San Antonio. Perdue and an undisclosed additional consideration go to the Spurs.','SAS CHI',ms('rodman','SAS','CHI')+ms('perdue c3-rodman95-other','CHI','SAS'),'c3-spurs96 c3-rodman95 c3-rodman95-undisclosed',notes=['The Spurs ledger and contemporary completed report give October 2. The additional consideration is preserved as undisclosed. Jack Haley’s separate free-agent signing is not placed in this exchange.'],short='Rodman goes to Chicago')

for _id,_origin in [('c3-den07-iverson','DEN'),('c3-dal07-iverson','DAL')]:
 obligation(_id,f'{_origin} 2007 first-round obligation',_origin,2007,conditions='2007 first included in the Iverson package. Its original protection language is not enumerated by the cited completed announcement. No unverified rollover terms are added.')
tx('iverson-denver','2006-12-19','The Answer leaves Philadelphia.','Iverson and McFarlin go to Denver. Philadelphia receives Miller, Smith and two firsts with different franchise origins.','PHI DEN',ms('iverson mcfarlin','PHI','DEN')+ms('miller-andre smith-joe c3-den07-iverson c3-dal07-iverson','DEN','PHI'),'c3-iverson06 c3-iverson-pick-origins w2-denver24',short='Iverson goes to Denver')
selection('cook-draft','2007-06-28','PHI','c3-den07-iverson','cook','Daequan Cook',21,2007,'DEN',1,'c3-sixers24 w2-denver24','Denver’s first becomes Philadelphia’s No. 21 selection. Cook’s draft rights are about to enter another exchange.')
obligation('c3-phi09-cook-second','2009 second-round consideration',None,2009,2,conditions='A 2009 second sent by Philadelphia with Cook’s rights. The cited Miami release does not establish its originating franchise or additional conditions. It is not assigned a player outcome.')
cash('c3-cook07-cash','Philadelphia sent cash with Cook’s rights and the future second. Amount not asserted.')
tx('cook-miami','2007-06-28','One spot in the draft. Three assets.','Miami trades Smith’s draft rights for Cook’s rights, a future second and cash. The Denver pick’s player heads to South Florida.','PHI MIA',ms('cook','PHI','MIA','rights')+ms('c3-phi09-cook-second c3-cook07-cash','PHI','MIA')+ms('smith-jason','MIA','PHI','rights'),'c3-heat24 c3-sixers24',order=1,notes=['Smith was selected No. 20; Cook was No. 21. The future second is 2009, as Miami’s transaction ledger states.'],short='Cook’s rights go to Miami')
tx('iverson-detroit','2008-11-03','Iverson and Billups cross paths.','Denver sends Iverson to Detroit. Billups, McDyess and Samb head to Denver. Billups later joins the Carmelo Anthony package.','DEN DET',ms('iverson','DEN','DET')+ms('billups mcdyess samb','DET','DEN'),'c3-iverson08 w2-denver24',short='Iverson goes to Detroit')
for _id,_origin,_round,_number in [('c3-mia10-18','MIA',1,18),('c3-min10-32','MIN',2,32)]:
 assets[_id]=dict(id=_id,name=f'2010 No. {_number}',kind='pick',origin=_origin,year=2010,round=_round,number=_number)
tx('cook-oklahoma-city','2010-06-23','Cook travels with another first.','Miami sends Cook and its No. 18 pick to Oklahoma City. The Minnesota-origin No. 32 pick goes to Miami.','MIA OKC',ms('cook c3-mia10-18','MIA','OKC')+ms('c3-min10-32','OKC','MIA'),'c3-heat24 c3-draft10-order',notes=['These are established draft positions on the eve of the draft. Later pick transfers are not collapsed into this exchange. Cook’s Oklahoma City departure is the existing 2012 Harden trade.'],short='Cook and No. 18 go to Oklahoma City')

tx('mcgrady-houston','2004-06-29','Seven players. One new pairing.','McGrady, Howard, Lue and Gaines move from Orlando to Houston. Francis, Mobley and Cato form the package going to Orlando.','ORL HOU',ms('mcgrady howard-juwan lue gaines','ORL','HOU')+ms('francis mobley-cuttino cato','HOU','ORL'),'harden-guide c3-magic23',short='McGrady goes to Houston')
tx('francis-new-york','2006-02-22','Orlando’s return takes another turn.','Francis goes to New York. Orlando receives Ariza and Hardaway; Ariza’s next trade will take him to Los Angeles.','ORL NYK',ms('francis','ORL','NYK')+ms('ariza hardaway-anfernee','NYK','ORL'),'c3-magic23 w2-knicks18',short='Francis goes to New York')
tx('ariza-lakers','2007-11-20','Ariza enters the Lakers chapter.','Orlando trades Ariza to Los Angeles for Cook and Evans. The connection runs through Francis’s earlier package.','ORL LAL',ms('ariza','ORL','LAL')+ms('cook-brian evans-maurice','LAL','ORL'),'c3-ariza07 c3-magic23',short='Ariza goes to Los Angeles')
obligation('c3-nyk12-mcgrady','New York protected first','NYK',2012,conditions='Top five protected in 2012–2015. Later fallback terms are not verified here. The actual 2012 conveyance is recorded at No. 16.',protection=[dict(year=y,protectedRanges=[[1,5]]) for y in range(2012,2016)])
swap('c3-nyk11-mcgrady-swap','NYK',2011,'Houston can exchange its own 2011 first for New York’s, unless New York receives the No. 1 overall pick. This is a swap right, not a second outright first. The later exercise decision is outside this route.')
cash('c3-mcgrady10-cash','Houston sent cash to Sacramento in the completed three-team exchange; the Rockets ledger does not specify the amount.')
tx('mcgrady-new-york','2010-02-18','Nine players spread across three cities.','McGrady reaches New York. Houston receives Martin, Armstrong, Hill, Jeffries and draft consideration. Sacramento receives Landry, Dorsey, Hughes and cash.','HOU NYK SAC',ms('mcgrady','HOU','NYK')+ms('landry-carl dorsey c3-mcgrady10-cash','HOU','SAC')+ms('hill-jordan jeffries-jared c3-nyk12-mcgrady c3-nyk11-mcgrady-swap','NYK','HOU')+ms('hughes','NYK','SAC')+ms('martin armstrong-hilton','SAC','HOU')+ms('rodriguez-sergio','SAC','NYK'),'c3-mcgrady10-final harden-guide w2-knicks18 c3-mcgrady10-terms c3-mcgrady10-protection',notes=['The final completed three-team package is one event. McGrady is not routed through Sacramento on the basis of an earlier proposal.','Martin and Hill later enter different packages. Neither alone represents the entire return from this exchange.'],short='McGrady’s nine-player New York trade')
selection('white-royce-draft','2012-06-28','HOU','c3-nyk12-mcgrady','white-royce','Royce White',16,2012,'NYK',1,'harden-guide c3-mcgrady-pick-outcome','New York’s first conveys outside the protected top five. Houston uses No. 16 on Royce White.')

# Restore the first protection year of the SAME obligation already used by Harden.
assets['dal13']['year']=2012
assets['dal13']['conditions']='Top 20 protected in 2012–2017; unprotected in 2018. First sent to the Lakers for Lamar Odom in December 2011, then to Houston for Jordan Hill, then to Oklahoma City in the Harden package.'
assets['dal13']['protection']=[dict(year=y,protectedRanges=[[1,20]]) for y in range(2012,2018)]+[dict(year=2018,protectedRanges=[])]
assets['dal13']['sources']=list(dict.fromkeys(assets['dal13'].get('sources',[])+['c3-odom11-terms','harden-protections']))
obligation('c3-lal12-odom-second','Lakers 2012 second','LAL',2012,2,conditions='Lakers-origin 2012 second included in the Odom package. Actual conveyance is recorded at No. 55.')
swap('c3-lal13-odom-swap','LAL',2013,'Dallas may exchange its own 2013 second-round pick for the Lakers’ own 2013 second. This is a second-round swap, not a first-round entitlement.')
assets['c3-lal13-odom-swap']['round']=2
assets['c3-lal13-odom-swap']['name']='2013 Lakers second-round swap right'
tx('odom-dallas','2011-12-11','Dallas sends a first into the future.','Dallas acquires Odom, a Lakers second and a later second-round swap. Its protected first begins a journey through three teams.','DAL LAL',ms('odom c3-lal12-odom-second c3-lal13-odom-swap','LAL','DAL')+ms('dal13','DAL','LAL'),'dx-dallas25 c3-odom11-terms',notes=['Los Angeles generated a traded-player exception. That is cap capacity created by the deal, not a transferred asset.','The 2013 consideration is a second-round swap. The protected Dallas first is the same obligation later received by Houston and Oklahoma City.'],short='Odom goes to Dallas')
tx('hill-jordan-lakers','2012-03-15','The Dallas obligation moves again.','Houston sends Hill to the Lakers. Fisher and the protected Dallas first go to Houston, where the pick will join the Harden package.','HOU LAL',ms('hill-jordan','HOU','LAL')+ms('fisher dal13','LAL','HOU'),'c3-hill12 harden-guide c3-odom11-terms',short='Hill for Fisher and Dallas’s first')
tx('dallas-pick-rolls-2012','2012-06-28','No. 17 stays with Dallas.','Dallas lands inside the top-20 protection. Houston still holds the future obligation; a new pick has not been added.','DAL HOU',[],'dx-dallas25 c3-odom11-terms',kind='resolution',resolutions=[dict(asset='dal13',status='deferred',detail='Dallas’s 2012 first is No. 17, within the protected range. The same obligation rolls to 2013.')],short='Dallas’s first rolls to 2013')
selection('johnson-odom-draft','2012-06-28','DAL','c3-lal12-odom-second','johnson-odom','Darius Johnson-Odom',55,2012,'LAL',2,'dx-dallas25 c3-odom11-terms','The Lakers second from the Odom package conveys at No. 55. Dallas selects Darius Johnson-Odom.')
transactions[-1]['order']=1
cash('c3-johnson-odom12-cash','Los Angeles purchased Johnson-Odom’s draft rights for cash; the team ledger does not specify the amount.')
tx('johnson-odom-lakers','2012-06-28','The second’s player goes back to L.A.','Dallas sends Johnson-Odom’s newly selected rights to the Lakers for cash. The draft selection and rights trade are separate events.','DAL LAL',ms('johnson-odom','DAL','LAL','rights')+ms('c3-johnson-odom12-cash','LAL','DAL'),'c3-djo12',order=2,notes=['Los Angeles’s historical transaction ledger dates the rights acquisition June 28. This follows the draft-night event date.'],short='Johnson-Odom’s rights return to Los Angeles')

# New roots share canonical packages; no duplicated Harden or Carmelo records.
story('kareem','Kareem changes coast','The skyhook.\nThe other side.','A Los Angeles landmark begins with six names. Follow one of Milwaukee’s rookies into a second six-player trade.','Classic',1975,1984,'LAL','#eac55b','kareem-lakers cummings-milwaukee','kareem-lakers','The complete 1975 exchange and Bridgeman’s inclusion in the 1984 Clippers–Bucks package. Stops September 29, 1984; later trades and career milestones are not treated as trade returns.','Bridgeman’s rights were one part of Milwaukee’s return. Nine years later, he joined a package for Cummings, Hodges and Pierce.')
story('pippen','Pippen’s Dallas detour','Follow the six\nwho came back.','Seattle to Chicago to Houston to Portland. Then follow Kelvin Cato, a Dallas draft choice in Pippen’s six-player return.','Classic',1987,2014,'CHI','#ee8493','pippen-chicago cato-portland pippen-houston pippen-portland mcgrady-houston mcgrady-new-york odom-dallas hill-jordan-lakers white-royce-draft dallas-pick-rolls-2012 harden-houston dallas-pick-rolls mcgary-draft','pippen-chicago','Pippen’s three trades, Cato’s Dallas origin, the complete McGrady packages, and the Jordan Hill–Dallas first–Harden route through 2014. The early Pippen draft considerations have untraced terms; no unsupported selection is assigned.','Cato connects Pippen’s Portland trade to McGrady’s Houston arrival. Hill and a protected Dallas first carry a later branch into the Harden package.')
story('rodman','The Worm changes sides','Detroit.\nSan Antonio. Chicago.','Two Rodman trades, Elliott’s return, and the small considerations that a headline leaves out.','Classic',1993,1995,'CHI','#ee8493','rodman-san-antonio morris-san-antonio elliott-san-antonio rodman-chicago','rodman-san-antonio','Rodman’s 1993 and 1995 exchanges, the separate same-day Morris deal, and Elliott’s completed July 1994 return. Stops October 2, 1995. Conditional seconds and swap outcomes are untraced; the additional 1995 consideration is explicitly undisclosed.','Elliott returned to San Antonio before Rodman left. These are separate completed exchanges, not a reversal that erased the first package.')
story('iverson','The Answer’s next questions','A pick connects\ntwo superstar trades.','Iverson leaves Philadelphia. A Denver first becomes Cook, who travels through Miami into the Harden exchange.','Classic',2006,2012,'PHI','#78aaff','iverson-denver cook-draft cook-miami iverson-detroit cook-oklahoma-city carmelo-new-york harden-houston','iverson-denver','Both Iverson trades, Denver’s 2007 first to Cook, Cook’s Miami and Oklahoma City packages, and shared Carmelo/Harden exchanges. Stops October 27, 2012; Dallas’s 2007 first and later pick branches are untraced.','Cook and Billups connect different sides of Iverson’s history to Harden and Carmelo. Each arrives in a package with other contributions.')
story('mcgrady','T-Mac’s branching return','The names behind\nthe headline.','McGrady’s trades branch toward Ariza, Martin and a protected Dallas first. Follow the entire packages to see where the paths meet.','Classic',2004,2014,'HOU','#f58389','mcgrady-houston francis-new-york ariza-lakers mcgrady-new-york odom-dallas hill-jordan-lakers white-royce-draft dallas-pick-rolls-2012 johnson-odom-draft johnson-odom-lakers harden-houston dallas-pick-rolls mcgary-draft','mcgrady-houston','The complete 2004 and 2010 McGrady trades; Francis to Ariza; Hill to the Dallas first; Odom’s 2012 second and its rights return; the shared Harden package and 2014 McGary conveyance. New York’s first conveys to Royce White. The 2011 New York swap and the Odom 2013 second-round swap remain bounded, untraced branches.','The Dallas first traveled through the Odom and Hill trades before joining Houston’s offer for Harden. It remained one obligation throughout.')
